# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DotenvDoctor < Formula
  desc "The dashboard for .env files you've lost track of, with built-in leak detection."
  homepage "https://github.com/zigamedved/dotenv-doctor"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/zigamedved/dotenv-doctor/releases/download/v0.1.0/dotenv-doctor_0.1.0_darwin_amd64.tar.gz"
      sha256 "d5bb7a3430ca2c499e4acfc4d236807a8123be21950aba2da1600a46f8b69541"

      define_method(:install) do
        bin.install "envs"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/zigamedved/dotenv-doctor/releases/download/v0.1.0/dotenv-doctor_0.1.0_darwin_arm64.tar.gz"
      sha256 "3a4ead3bc5a83aa62b800d93ba6745c9e6e41d2a7f2661e2e81e205625497b1c"

      define_method(:install) do
        bin.install "envs"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/zigamedved/dotenv-doctor/releases/download/v0.1.0/dotenv-doctor_0.1.0_linux_amd64.tar.gz"
      sha256 "a6c514814930a5a35daee256cd4bd2de0ee38a0a8e328b1bd5e7741381aafbcb"
      define_method(:install) do
        bin.install "envs"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zigamedved/dotenv-doctor/releases/download/v0.1.0/dotenv-doctor_0.1.0_linux_arm64.tar.gz"
      sha256 "83d1955696e4dbb18cb5afac81579a635f31357ef8b97d6d93431ffe175aea6e"
      define_method(:install) do
        bin.install "envs"
      end
    end
  end

  test do
    assert_match "envs version", shell_output("#{bin}/envs --version")
  end
end
