# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Chain < Formula
  desc "Supply chain risk visibility — know what you're running before you run it"
  homepage "https://github.com/zigamedved/chain"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/zigamedved/chain/releases/download/v0.1.0/chain_0.1.0_darwin_amd64.tar.gz"
      sha256 "e85e64da52f7453212a837cf2a9401e3ec823fd298fdbe5eaa977b2e55263fdc"

      define_method(:install) do
        bin.install "chain"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/zigamedved/chain/releases/download/v0.1.0/chain_0.1.0_darwin_arm64.tar.gz"
      sha256 "8435c52bcb072ae79020fe86e8ea527bd6f29cc3217ffb26bdf68b9b9c8f85f0"

      define_method(:install) do
        bin.install "chain"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/zigamedved/chain/releases/download/v0.1.0/chain_0.1.0_linux_amd64.tar.gz"
      sha256 "81254b3e27d7254927fb602adea44b1d992e214b64be28a0868c23e6075233be"
      define_method(:install) do
        bin.install "chain"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zigamedved/chain/releases/download/v0.1.0/chain_0.1.0_linux_arm64.tar.gz"
      sha256 "dea0b337ff60eb6ab796eaff51f8691add0113020917da0edd9e3cdfbc48608d"
      define_method(:install) do
        bin.install "chain"
      end
    end
  end
end
